/* eslint-disable */
// Generated by scripts/generate_types.py -- do not edit by hand.
// Regenerate with: uv run python scripts/generate_types.py

export type Chunker = "recursive" | "semantic" | "structure_entity" | "claim_centered"

export type IngestEffort = "manual" | "low" | "medium" | "high"

export type IngestMode = "regular" | "multimodal"

export type IssueLevel = "error" | "warning"

export type JobKind = "timer" | "reminder" | "email"

export type JobStatus = "pending" | "fired" | "cancelled"

export type Provider = "ollama" | "openai"

/** Retrieval strategy selected in chat and settings. */
export type QueryMode = "local" | "global" | "drift" | "auto"

export type RagMode = "regular" | "agentic"

export interface ApprovalDecision {
  request_id: string
  tool: string
  approved: boolean
}

/** A tool call the policy permits only with a human in the loop. */
export interface ApprovalRequiredEvent {
  type: "approval_required"
  id: string
  tool: string
  reason: string
  details: Record<string, unknown>
}

/** One prior chat turn. Client ``system`` roles are rejected at the API. */
export interface ChatMessage {
  role: "user" | "assistant"
  content: string
}

/** Incoming chat request payload (SSE stream on POST /api/chat). */
export interface ChatRequest {
  /** The user's message to the AI assistant */
  message: string
  history: ChatMessage[]
  profile: Profile
  /** Conversation thread ID */
  thread_id: string
  /** Alias for thread_id used by earlier clients */
  conversation_id: string | null
  approval_id: string | null
}

/** Non-streaming chat payload. */
export interface ChatResponse {
  response: string
  thread_id: string
  model_used: string
  cached: boolean
  processing_time_ms: number
  timestamp: string
}

/** A pointer back into the vault. */
export interface Citation {
  id: string
  note_path: string
  note_title: string
  heading_path: string[]
  snippet: string
  char_start: number
  char_end: number
  score: number
  source: "graph" | "vector" | "visual" | "link"
  page: number | null
}

export interface CitationsEvent {
  type: "citations"
  citations: Citation[]
}

export interface CreateJobRequest {
  kind: JobKind
  title: string
  body: string
  fire_at: string | null
  seconds_from_now: number | null
  payload: Record<string, unknown>
}

export interface DoneEvent {
  type: "done"
  message_id: string
  cancelled: boolean
  elapsed_ms: number
}

export interface ErrorEvent {
  type: "error"
  message: string
  code: string
  recoverable: boolean
}

/** Standard error body for failed HTTP requests (not SSE ErrorEvent). */
export interface ErrorResponse {
  error: string
  detail: string | null
  request_id: string | null
}

/** One GPU reported by a best-effort hardware probe. */
export interface GpuInfo {
  name: string
  vram_total_mb: number | null
  vram_free_mb: number | null
}

/** Health check response. */
export interface HealthResponse {
  status: string
  environment: string
  version: string
  ok: boolean
  checks: Record<string, unknown>
}

export interface IndexStatus {
  engine: string
  ready: boolean
  indexing: boolean
  indexing_stale: boolean
  total_notes: number
  indexed_notes: number
  stale_notes: number
  entities: number
  relationships: number
  communities: number
  embedding_model: string | null
  extraction_model: string | null
  last_indexed_at: string | null
}

export interface Job {
  id: string
  kind: JobKind
  title: string
  body: string
  fire_at: string
  created_at: string
  fired_at: string | null
  status: JobStatus
  payload: Record<string, unknown>
  missed: boolean
}

/** Metrics endpoint response. */
export interface MetricsResponse {
  total_requests: number
  total_errors: number
  error_rate: string
  avg_latency_ms: number
  cache_hit_rate: string
  total_input_tokens: number
  total_output_tokens: number
  config_changes: number
  rate_limit_denials: number
  rate_limit_exemptions: number
}

export interface ModelInfo {
  id: string
  provider: Provider
  label: string
  context_window: number
  supports_vision: boolean
  supports_tools: boolean
  is_embedding: boolean
  dimensions: number | null
  available: boolean
  unavailable_reason: string | null
  parameter_b: number | null
  est_vram_mb: number | null
  size_bytes: number | null
  hf_id: string | null
  role_scores: Record<string, number> | null
  tier: string | null
}

/** One ranked candidate for a role. */
export interface ModelRecommendation {
  id: string
  provider: Provider
  score: number
  reasons: string[]
  fits: boolean
  needs_pull: boolean
  metrics_degraded: boolean
  available: boolean
  disabled_reason: string
}

export interface OptionValidity {
  field: string
  value: string
  valid: boolean
  reason: string
}

export interface OptionsResponse {
  chat_models: ModelInfo[]
  embedding_models: ModelInfo[]
  query_modes: Record<string, string>[]
  rag_modes: Record<string, string>[]
  chunkers: Record<string, string>[]
  ingest_modes: Record<string, string>[]
  ingest_efforts: Record<string, string>[]
}

/** The machine-enforced half of ``config/rules.md``. */
export interface Policy {
  version: number
  allow_delete: boolean
  allow_download: boolean
  allow_shell: boolean
  allow_network: boolean
  allow_email_send: boolean
  allow_vault_write: boolean
  vault_path: string
  allowed_read_paths: string[]
  allowed_write_paths: string[]
  denied_paths: string[]
  trash_dir: string
  quarantine_dir: string
  require_approval_for: string[]
  max_file_writes_per_turn: number
  max_tool_calls_per_turn: number
  max_download_bytes: number
  allowed_tools: string[]
  prompt_text: string
}

/** One coherent configuration. */
export interface Profile {
  id: string
  name: string
  chat_model: string
  chat_provider: Provider
  voice_model: string
  voice_provider: Provider
  embedding_model: string
  embedding_provider: Provider
  rag_mode: RagMode
  query_mode: QueryMode
  ingest_mode: IngestMode
  ingest_effort: IngestEffort
  chunker: Chunker
  chunk_size: number
  chunk_overlap: number
  chunk_decision_model: string
  chunk_decision_provider: Provider
  extraction_model: string
  extraction_provider: Provider
  rerank_model: string
  rerank_provider: Provider
  agentic_max_iters: number
  rrf_k: number
  hybrid_vector_top_k: number
  hybrid_keyword_top_k: number
  prepend_note_context: boolean
  expand_to_parent: boolean
  community_level: number
  max_context_tokens: number
  top_k: number
  tracing_enabled: boolean
  model_metrics_online: boolean
}

/** Which choices would break the current profile, and why. */
export interface ProfileMatrix {
  current: ProfileValidation
  options: OptionValidity[]
}

export interface ProfileValidation {
  valid: boolean
  issues: ValidationIssue[]
}

/** Rank catalog models for one or more profile roles. */
export interface RecommendRequest {
  roles: string[] | null
  apply: boolean
  top_n: number
  online: boolean | null
  profile: Profile | null
}

/** Per-role ranked recommendations plus the system snapshot used to score. */
export interface RecommendResponse {
  roles: RoleRecommendation[]
  system: SystemInfo
  online: boolean
  metrics_degraded: boolean
}

export interface RetrievalProgressEvent {
  type: "retrieval_progress"
  current: number
  total: number
  label: string
}

export interface RetrievalStartEvent {
  type: "retrieval_start"
  mode: QueryMode
  label: string
  estimated_calls: number
  estimated_seconds: number | null
}

/** Ranked shortlist for a single profile role. */
export interface RoleRecommendation {
  role: string
  recommendations: ModelRecommendation[]
  metrics_degraded: boolean
}

/** Local machine specs used to gate and score model recommendations. */
export interface SystemInfo {
  ram_total_mb: number | null
  ram_available_mb: number | null
  cpu_cores: number | null
  gpus: GpuInfo[]
  probe_errors: string[]
}

export interface TokenEvent {
  type: "token"
  text: string
}

export interface ToolCallEvent {
  type: "tool_call"
  id: string
  name: string
  arguments: Record<string, unknown>
}

export interface ToolResultEvent {
  type: "tool_result"
  id: string
  name: string
  ok: boolean
  result: string
}

/** Text to synthesize with the local Fish Speech server. */
export interface TtsRequest {
  text: string
}

/** Whether Fish Speech TTS is enabled and the local server is up. */
export interface TtsStatus {
  enabled: boolean
  ready: boolean
  engine: string
  model: string
  base_url: string
}

export interface ValidationIssue {
  level: IssueLevel
  field: string
  message: string
}

export type StreamEvent =
  | TokenEvent
  | RetrievalStartEvent
  | RetrievalProgressEvent
  | CitationsEvent
  | ToolCallEvent
  | ToolResultEvent
  | ApprovalRequiredEvent
  | ErrorEvent
  | DoneEvent

/** Lets a handler map narrow to the right event by its discriminator. */
export interface StreamEventMap {
  "token": TokenEvent
  "retrieval_start": RetrievalStartEvent
  "retrieval_progress": RetrievalProgressEvent
  "citations": CitationsEvent
  "tool_call": ToolCallEvent
  "tool_result": ToolResultEvent
  "approval_required": ApprovalRequiredEvent
  "error": ErrorEvent
  "done": DoneEvent
}

export type StreamEventType = keyof StreamEventMap
