"""Emit the TypeScript mirror of app.models.

Run after changing any model:
    uv run python scripts/generate_types.py

Emits plain type aliases rather than TS enums because the frontend compiles
with ``erasableSyntaxOnly``, which forbids enums.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from pydantic import BaseModel  # noqa: E402

from app import models as m  # noqa: E402
from app import scheduler as sched  # noqa: E402
from app import security as sec  # noqa: E402

OUTPUT = Path(__file__).resolve().parent.parent / "frontend" / "src" / "lib" / "api" / "types.ts"

ROOTS: tuple[type[BaseModel], ...] = (
    m.ModelInfo,
    m.Profile,
    m.ValidationIssue,
    m.ProfileValidation,
    m.OptionValidity,
    m.ProfileMatrix,
    m.Citation,
    m.IndexStatus,
    m.TokenEvent,
    m.RetrievalStartEvent,
    m.RetrievalProgressEvent,
    m.CitationsEvent,
    m.ToolCallEvent,
    m.ToolResultEvent,
    m.ApprovalRequiredEvent,
    m.ErrorEvent,
    m.DoneEvent,
    m.ChatMessage,
    m.ChatRequest,
    m.ChatResponse,
    m.HealthResponse,
    m.MetricsResponse,
    m.ErrorResponse,
    m.ApprovalDecision,
    m.OptionsResponse,
    m.GpuInfo,
    m.SystemInfo,
    m.RecommendRequest,
    m.ModelRecommendation,
    m.RoleRecommendation,
    m.RecommendResponse,
    m.TtsRequest,
    m.TtsStatus,
    sec.Policy,
    sched.Job,
    sched.CreateJobRequest,
)

EVENT_MODELS = (
    m.TokenEvent,
    m.RetrievalStartEvent,
    m.RetrievalProgressEvent,
    m.CitationsEvent,
    m.ToolCallEvent,
    m.ToolResultEvent,
    m.ApprovalRequiredEvent,
    m.ErrorEvent,
    m.DoneEvent,
)

PRIMITIVES = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def collect() -> dict[str, dict[str, Any]]:
    definitions: dict[str, dict[str, Any]] = {}
    for model in ROOTS:
        schema = model.model_json_schema(ref_template="#/$defs/{model}")
        for name, sub in schema.pop("$defs", {}).items():
            definitions.setdefault(name, sub)
        definitions.setdefault(schema.get("title", model.__name__), schema)
    return definitions


def ts_type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]

    if "const" in node:
        return json.dumps(node["const"])

    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])

    for key in ("anyOf", "oneOf"):
        if key in node:
            parts = [ts_type(entry) for entry in node[key]]
            unique = list(dict.fromkeys(parts))
            return " | ".join(unique) if unique else "unknown"

    if "allOf" in node and len(node["allOf"]) == 1:
        return ts_type(node["allOf"][0])

    node_type = node.get("type")

    if node_type == "array":
        items = node.get("items")
        return f"{ts_type(items)}[]" if items else "unknown[]"

    if node_type == "object":
        extra = node.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Record<string, {ts_type(extra)}>"
        return "Record<string, unknown>"

    if isinstance(node_type, list):
        return " | ".join(PRIMITIVES.get(t, "unknown") for t in node_type)

    if node_type == "string" and node.get("format") in {"date-time", "date"}:
        return "string"

    return PRIMITIVES.get(node_type, "unknown")


def emit_definition(name: str, schema: dict[str, Any]) -> str:
    description = schema.get("description", "").strip().splitlines()
    doc = ""
    if description:
        doc = "/** " + description[0].strip() + " */\n"

    if "enum" in schema and "properties" not in schema:
        values = " | ".join(json.dumps(v) for v in schema["enum"])
        return f"{doc}export type {name} = {values}\n"

    properties: dict[str, Any] = schema.get("properties", {})
    if not properties:
        return f"{doc}export type {name} = Record<string, unknown>\n"

    lines = [f"{doc}export interface {name} {{"]
    for prop, node in properties.items():
        rendered = ts_type(node)
        comment = (node.get("description") or "").strip().splitlines()
        if comment:
            lines.append(f"  /** {comment[0].strip()} */")
        lines.append(f"  {prop}: {rendered}")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_types() -> str:
    """Build the TypeScript types file contents without writing to disk."""
    definitions = collect()

    chunks: list[str] = [
        "/* eslint-disable */",
        "// Generated by scripts/generate_types.py -- do not edit by hand.",
        "// Regenerate with: uv run python scripts/generate_types.py",
        "",
    ]

    enums = {k: v for k, v in definitions.items() if "enum" in v and "properties" not in v}
    objects = {k: v for k, v in definitions.items() if k not in enums}

    for name in sorted(enums):
        chunks.append(emit_definition(name, enums[name]))

    for name in sorted(objects):
        chunks.append(emit_definition(name, objects[name]))

    union = "\n  | ".join(model.__name__ for model in EVENT_MODELS)
    chunks.append(f"export type StreamEvent =\n  | {union}\n")

    mapping = "\n".join(
        f"  {json.dumps(model.model_fields['type'].default)}: {model.__name__}"
        for model in EVENT_MODELS
    )
    chunks.append(
        "/** Lets a handler map narrow to the right event by its discriminator. */\n"
        f"export interface StreamEventMap {{\n{mapping}\n}}\n"
    )
    chunks.append("export type StreamEventType = keyof StreamEventMap\n")
    return "\n".join(chunks)


def main() -> int:
    """Write generated types to ``OUTPUT`` and optionally format with Prettier."""
    text = render_types()
    definitions = collect()

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")

    formatted = _prettier(OUTPUT)
    print(f"Wrote {OUTPUT.relative_to(Path.cwd())}"
          f" ({len(definitions)} definitions{', formatted' if formatted else ''})")
    return 0


def _prettier(path: Path) -> bool:
    """Best effort: keep the output tidy if prettier happens to be available."""
    try:
        subprocess.run(
            ["npx", "--no-install", "prettier", "--write", str(path)],
            check=True, capture_output=True, shell=sys.platform == "win32", timeout=60,
        )
    except (OSError, subprocess.SubprocessError):
        return False
    return True


if __name__ == "__main__":
    raise SystemExit(main())
